/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#464555",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "outline": "#777587",
        "outline-variant": "#c7c4d8",
        "surface-tint": "#4d44e3",
        "primary": "#3525cd",
        "on-primary": "#ffffff",
        "primary-container": "#4f46e5",
        "on-primary-container": "#dad7ff",
        "inverse-primary": "#c3c0ff",
        "secondary": "#6b38d4",
        "on-secondary": "#ffffff",
        "secondary-container": "#8455ef",
        "on-secondary-container": "#fffbff",
        "tertiary": "#005338",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#006e4b",
        "on-tertiary-container": "#67f4b7",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-fixed": "#0f0069",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#5516be",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "background": "#faf8ff",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd",

        // FSRS Specialized Semantics
        "fsrs-again": "#f43f5e",
        "fsrs-again-bg": "#fff1f2",
        "fsrs-again-border": "#fecdd3",
        "fsrs-again-text": "#e11d48",

        "fsrs-hard": "#f59e0b",
        "fsrs-hard-bg": "#fffbeb",
        "fsrs-hard-border": "#fde68a",
        "fsrs-hard-text": "#d97706",

        "fsrs-good": "#10b981",
        "fsrs-good-bg": "#ecfdf5",
        "fsrs-good-border": "#a7f3d0",
        "fsrs-good-text": "#059669",

        "fsrs-easy": "#0ea5e9",
        "fsrs-easy-bg": "#f0f9ff",
        "fsrs-easy-border": "#bae6fd",
        "fsrs-easy-text": "#0284c7",

        "ai-proposal": "#8b5cf6",
        "ai-proposal-bg": "#f5f3ff",
        "ai-proposal-border": "#ddd6fe",
        "ai-proposal-text": "#7c3aed"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        gutter: "1.5rem",
        margin: "2rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "code-inline": ["JetBrains Mono", "monospace"],
        "code-block": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
        "code-inline": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "code-block": ["13px", { lineHeight: "20px", fontWeight: "400" }],
      }
    },
  },
  plugins: [],
};
