-- +goose Up
-- FSRS 调度, 复习历史与每日日历计数.

CREATE TABLE card_schedule (
    card_id         BIGINT      NOT NULL PRIMARY KEY,
    due             TIMESTAMPTZ NOT NULL,
    stability       DOUBLE PRECISION NOT NULL,
    difficulty      DOUBLE PRECISION NOT NULL,
    scheduled_days  BIGINT      NOT NULL,
    reps            BIGINT      NOT NULL,
    lapses          BIGINT      NOT NULL,
    state           SMALLINT    NOT NULL,
    last_review_at  TIMESTAMPTZ NULL,
    remaining_steps BIGINT      NOT NULL,
    version         BIGINT      NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_card_schedule_due ON card_schedule (due);
CREATE INDEX idx_card_schedule_state_due ON card_schedule (state, due);

CREATE TABLE review_log (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id         BIGINT      NOT NULL,
    rating          SMALLINT    NOT NULL,
    due             TIMESTAMPTZ NOT NULL,
    scheduled_days  BIGINT      NOT NULL,
    reviewed_at     TIMESTAMPTZ NOT NULL,
    state           SMALLINT    NOT NULL,
    stability       DOUBLE PRECISION NOT NULL,
    difficulty      DOUBLE PRECISION NOT NULL,
    remaining_steps BIGINT      NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_review_log_card_reviewed ON review_log (card_id, reviewed_at, id);
CREATE INDEX idx_review_log_reviewed_at ON review_log (reviewed_at);

CREATE TABLE calendar (
    activity_date DATE        NOT NULL PRIMARY KEY,
    created_cards BIGINT      NOT NULL DEFAULT 0,
    review_events BIGINT      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS calendar;
DROP TABLE IF EXISTS review_log;
DROP TABLE IF EXISTS card_schedule;
