-- +goose Up
-- CLI 审批队列与幂等记录.

CREATE TABLE approval_request (
    id                      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation               SMALLINT     NOT NULL,
    entity_type             SMALLINT     NOT NULL,
    status                  SMALLINT     NOT NULL,
    requested_by_api_key_id BIGINT       NULL,
    original_payload        TEXT         NOT NULL,
    approved_payload        TEXT         NULL,
    reason                  TEXT         NULL,
    created_at              TIMESTAMPTZ  NOT NULL,
    processed_at            TIMESTAMPTZ  NULL
);

CREATE INDEX idx_approval_request_status_created ON approval_request (status, created_at, id);
CREATE INDEX idx_approval_request_api_key_created ON approval_request (requested_by_api_key_id, created_at);
CREATE INDEX idx_approval_request_entity_status ON approval_request (entity_type, operation, status);

CREATE TABLE approval_target (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_request_id BIGINT      NOT NULL,
    entity_type         SMALLINT    NOT NULL,
    entity_id           BIGINT      NOT NULL,
    base_version        BIGINT      NOT NULL,
    role                VARCHAR(50) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_approval_target_request ON approval_target (approval_request_id, id);
CREATE INDEX idx_approval_target_entity ON approval_target (entity_type, entity_id, approval_request_id);
CREATE UNIQUE INDEX uq_approval_target_role ON approval_target (approval_request_id, entity_type, entity_id, role);

CREATE TABLE idempotency_record (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id      BIGINT       NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_method  VARCHAR(10)  NOT NULL,
    request_path    VARCHAR(500) NOT NULL,
    request_hash    VARCHAR(64)  NOT NULL,
    response_status BIGINT       NULL,
    response_body   TEXT         NULL,
    state           SMALLINT     NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL,
    expires_at      TIMESTAMPTZ  NOT NULL
);

CREATE UNIQUE INDEX uq_idempotency_key ON idempotency_record (api_key_id, idempotency_key);
CREATE INDEX idx_idempotency_expires_at ON idempotency_record (expires_at);

-- +goose Down
DROP TABLE IF EXISTS idempotency_record;
DROP TABLE IF EXISTS approval_target;
DROP TABLE IF EXISTS approval_request;
