-- +goose Up
-- 可选的轻量数据库日志.

CREATE TABLE app_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logged_at   TIMESTAMPTZ  NOT NULL,
    level       SMALLINT     NOT NULL,
    event       VARCHAR(100) NOT NULL,
    message     TEXT         NOT NULL,
    request_id  VARCHAR(100) NULL,
    source      SMALLINT     NULL,
    entity_type SMALLINT     NULL,
    entity_id   BIGINT       NULL,
    details     TEXT         NULL
);

CREATE INDEX idx_app_log_logged_id ON app_log (logged_at, id);
CREATE INDEX idx_app_log_level_logged ON app_log (level, logged_at);
CREATE INDEX idx_app_log_event_logged ON app_log (event, logged_at);
CREATE INDEX idx_app_log_request_id ON app_log (request_id);

-- +goose Down
DROP TABLE IF EXISTS app_log;
