-- +goose Up
-- 知识内容: topic, card, trashed_card, glossary.

CREATE TABLE topic (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    description TEXT         NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 1,
    trashed_at  TIMESTAMPTZ  NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_topic_name ON topic (name);
CREATE INDEX idx_topic_trashed_updated ON topic (trashed_at, updated_at);

CREATE TABLE card (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id          BIGINT      NULL,
    front             TEXT        NOT NULL,
    back              TEXT        NOT NULL,
    enable_embedding  BOOLEAN     NOT NULL,
    front_fingerprint BYTEA       NOT NULL,
    version           BIGINT      NOT NULL DEFAULT 1,
    embedding         BYTEA       NULL,
    embedding_status  SMALLINT    NULL,
    embedding_error   TEXT        NULL,
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_card_topic_updated ON card (topic_id, updated_at);
CREATE INDEX idx_card_created_at ON card (created_at);
CREATE INDEX idx_card_fingerprint_enabled ON card (front_fingerprint, enable_embedding);
CREATE INDEX idx_card_embedding_status ON card (embedding_status, id);

CREATE TABLE trashed_card (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    front            TEXT        NOT NULL,
    back             TEXT        NOT NULL,
    enable_embedding BOOLEAN     NOT NULL,
    version          BIGINT      NOT NULL DEFAULT 1,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    trashed_at       TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_trashed_card_trashed_id ON trashed_card (trashed_at, id);

CREATE TABLE glossary (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term       VARCHAR(200) NOT NULL,
    definition TEXT         NOT NULL,
    version    BIGINT       NOT NULL DEFAULT 1,
    trashed_at TIMESTAMPTZ  NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_glossary_term ON glossary (term);
CREATE INDEX idx_glossary_trashed_updated ON glossary (trashed_at, updated_at);

-- +goose Down
DROP TABLE IF EXISTS glossary;
DROP TABLE IF EXISTS trashed_card;
DROP TABLE IF EXISTS card;
DROP TABLE IF EXISTS topic;
